name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Instalar dependencias (si las hubiera)
      run: |
        python -m pip install --upgrade pip

    - name: Ejecutar pruebas
      run: |
        python test_calculadora.py
